- src/index.html
> Remove comments from index.

- src/common/addlayers/ServerService.js
- src/common/addlayers/ServerService.spec.js
This PR replaces the `d_docs_limit` arg with `from` in the elastic search query.
> Fix query in elastic search

- src/common/addlayers/ServerService.js
- src/common/addlayers/partials/addlayersfilter.tpl.html
No need evaluate whether registry is enabled.
> Remove registryEnabled check from getCatalog

- src/common/addlayers/ServerService.js
This PR replaces the hardcoded protocol in the wfs request to Django.
> Remove hardcoded protocol from wfs request 

- src/common/addlayers/ServerService.js
- src/common/addlayers/partials/registryLayers.tpl.html
- src/common/addlayers/style/addlayers.less
Display reliability information of the layers.
> Reliability

- src/app/app.less
- src/common/addlayers/RegistryLayersDirective.js
- src/common/addlayers/RegistryLayersDirective.spec.js
- src/common/addlayers/ServerService.js
- src/common/addlayers/ServerService.spec.js
- src/common/addlayers/partials/registryLayers.tpl.html
- src/common/addlayers/style/addlayers.less
- src/common/map/MapDirective.js
- src/common/map/MapService.js
Updates for Registry 0.3.9 and Exchange 1.0.2
- Custom tags available in MapLoom UI.
- Full screen MapLoom Registry modal.
- Adaptive pagination based on available height.
- Fixed map display issues on hover for ArcGIS layers.
- Switched to q.param and a.param instead of a_param and q_param for future compatibility with angular-search.
> Updates for Registry 0.3.9 and Exchange 1.0.2

- src/common/layers/partials/layers.tpl.html
- src/common/map/MapService.js
This PR fixes the error when attempting to display the layer heatmap.
* Properly handle the GeoJSON response
* Pass the correct argument type into the ol tile function
https://issues.boundlessgeo.com:8443/browse/NODE-335
> Enable heatmap menu item and fix service wfs response handling.

- bower.json
- build.config.js
- src/common/layers/partials/layers.tpl.html
- Adds code-fork icon
- Adds font awesome dependency
> Adds font-awesome code-fork icon to designate GeoGig layers

- src/app/PulldownController.js
- src/app/locales/en.js
- src/app/locales/es.js
- src/common/configuration/ConfigService.js
- src/index.html
- Allows the visibility of the nominatim search box to be toggled via a configuration param. Default behavior is hidden.
- Fixed typo in local geoserver source path from /web to /wms
> Adds a configurable property to hide the OSM nominatim search box

- src/common/addlayers/partials/registryLayers.tpl.html
- src/common/configuration/ConfigService.js
- src/common/map/MapDirective.js
- src/index.html
Fixes a major a bug in the Map directive that made it dependent on the registry layer dialog.
> Map directive dialog fix

- src/app/LoomModule.js
- src/app/app.less
- src/app/locales/en.js
- src/app/locales/es.js
- src/common/measure/MeasureModule.js
- src/common/measure/MeasurePanelDirective.js
- src/common/measure/partials/measurePanel.tpl.html
- src/common/measure/style/measure.less
- src/index.html
- src/less/main.less
Adds a new panel to MapLoom's control panel for making measurements.
NODE-130
> Add a Measuring Tool to 

- src/common/map/MapService.js
- src/common/refresh/RefreshService.js
This PR enables all layers to be refreshed based on the refreshTimeout interval.
> Enable refresh of all layers.

- src/common/legend/LegendDirective.js
- src/common/legend/LegendDirective.spec.js
Fixes bug with GetLegendGraphic generation when the OAuth token is included in the URL.
NODE-657
> Fix for GetLegendGraphic + OAuth

- src/common/map/partial/savemap.tpl.html
- src/less/exchange.less
Additional styling fixes for some of the dialogs which had ID-hard-coded styling.
NODE-654
> More styling fixes for the 'black' Exchange theme.

- src/common/map/MapService.js
Adds location tracking via the document hash.
NODE-677
> Track location in the browser hash

- src/less/exchange.less
Styling fixes for panels that were not working
during the last update pass.
NODE-729
> Additional styling fix for history and diff panels

- src/common/addlayers/ServerService.js
- src/common/addlayers/UnifiedSearchDirective.js
- src/common/addlayers/UnifiedSearchDirective.spec.js
No longer searching both the Registry instance
and GeoNode. It will now only search using the
/api/base/search endpoint.
No changes in visual presentation.
NODE-759, NODE-760, NODE-763
> Converted unified add layers to use new API.

- src/common/diff/DiffListDirective.js
In most examples, the map is in WebMercator and the layer is sourced
from a WGS84/EPSG:4326 dataset.  This adds projection sensing support
for the layer.  It defaults to the layer's data being in WGS84 if for
some reason a valid CRS cannot be found.
An "after" shot with the fixed projection handling.
NODE-749
> Fix for history zooming.

- src/app/locales/en.js
- src/app/locales/es.js
- src/common/addlayers/partials/unifiedLayerSearch.tpl.html
- src/common/addlayers/style/addlayers.less
1. Moved the keyword word search to the top and made
the search button more clear.
2. Adjusted heights in order to fix some rendering quirks.
NODE-783
> Re-arranged add layers dialog for clarity.

- src/common/map/MapService.js
Updated MapService to check the query string for the
existance of 'layer' keys that have 'registry:[uuid]' values.
Each value is then queried against the registry server and
addd to the map based on what's returned.
NODE-807
> Add the ability to load registry layers on startup.

- src/app/PulldownController.js
- src/common/configuration/ConfigService.js
- src/common/search/SearchService.js
- src/index.html
Generalizes search and allows for integration of GeoQuery search endpoint.
N/A (it just allows changing the endpoint in the search bar, nothing visible in UI)
N/A
> Integrate GeoQuery into MapLoom

- src/app/locales/en.js
- src/common/featuremanager/FeatureInfoBoxDirective.js
- src/common/featuremanager/FeatureManagerService.js
- src/common/featuremanager/partial/featureinfobox.tpl.html
- src/common/map/MapService.js
- src/common/search/SearchService.js
Allows search results to be selected on the map in order to display metadata related to the search, similar to any other layer.
Also, allows these points to be pinned to the map so that they remain even after the search has been cleared.
N/A
> Geoquery data and pin

- src/common/search/SearchService.js
Adjusts the GeoQuery request to function cross domain.
N/A
[NODE-908](https://issues.boundlessgeo.com:8443/browse/NODE-908)
> Updated GeoQuery search request to function cross domain

- src/app/locales/en.js
- src/app/locales/es.js
- src/common/addlayers/UnifiedSearchDirective.js
- src/common/addlayers/partials/unifiedLayerSearch.tpl.html
- src/common/addlayers/style/addlayers.less
1. Added new help text for when the user gets zero results.
2. Added the translations.
3. Updated some styling to support the new lists.
Most of the code here re-used the functional bits of other parts of the UI (isSet, clear()).
NODE-855
> Created better help for 0 results.

- src/app/locales/en.js
https://ci.boundlessps.com/job/commit-build-maploom/172
> pass gjslint

- src/common/addlayers/ServerService.js
> Address condition where dict is case sensitive

- README.md
Slight adjustment to docs
N/A
N/A
> Add quick-setup to README

- src/common/featuremanager/style/featuremanager.less
- src/common/legend/style/legend.less
Updated to PR #107 with passing tests.
> BEX-383 / Popups under Legend

- src/common/layers/partials/layers.tpl.html
- src/common/layers/style/layers.less
> fix overflow of style name

- src/common/featuremanager/FeatureManagerService.js
- src/common/featuremanager/FeatureManagerService.spec.js
- src/common/tableview/TableViewDirective.js
- src/common/utils/Globals.js
1. Created new escapeXml function which replaces
common "bad" entities.
2. Added a test for that function.
3. Added calls to escapeXml where pertinent in both
the feature manager service and the table view.
4. Added test for the FeatureManagerService which catches
when a property is updated.
BEX-28
> Fix for BEX-28, Escaping XML Chars.

- src/common/addlayers/ServerService.js
This restores the get caps functionality.
> Undo the removal of getcapabilities

- src/common/featuremanager/FeatureManagerService.js
The return from WMS GetFeatureInfo is sometimes returned in a
projection other than the one requested. On QA it was returning
as 4326 when 900913 was requested.  The new code will read
the projection of the incoming GeoJSON and then project the features
to the map projection.
BEX-455
> Normalize feature projection for popups

- src/app/locales/en.js
- src/app/locales/es.js
- src/common/layers/LayerInfoDirective.js
- src/common/layers/LayersDirective.js
- src/common/layers/partials/layers.tpl.html
- src/common/layers/style/layers.less
- src/common/map/MapService.js
- src/common/modal/style/modal.less
Relies on api call to Geoserver for the layer style information.
Displays an error message when there is an issue updating the style.
Hides the style controls if the layer doesn't have an associated style in Geoserver.
> grab style information from geoserver rather than geonode.

- src/common/map/MapService.js
This PR will safely create a new style and set it as the default for the layer if the current default style is one of points.sld, polygon.sld, line.sld, raster.sld.
> create a new style if using one of the defaults.

- src/common/addlayers/UnifiedSearchDirective.js
Updates for new elasticsearch app changes
> Updating search directive for new layer index

- bower.json
- src/common/layers/partials/layers.tpl.html
This points to the fork and branch with the latest
style-editor updates.
BEX-585
> Update story-tools to use the boundless fork

- src/common/layers/partials/layers.tpl.html
Limits the user to simple and unique styles only.
BEX-571
> Limit the styles avilable to the user

- src/common/addlayers/ServerService.js
- src/common/diff/FeatureDiffDirective.js
- src/common/map/MapService.js
Fix for the BBOX missing CRS
Provides an additional check to ensure that the BBOX
is found for zooming to extent.
Also fixes a bug for when a WMS GetCaps has no layers.
BEX-557
> Fix for the CRS Bug

- src/common/map/MapService.js
Potentially fixes PSBEX-92. May also be able to apply this fix in the ConfigService, or it might even be the proper place to do so.
N/A
[PSBEX-92]
> Potentially fixing double proxy issues

- src/common/map/MapService.js
Send sld request to the Geonode proxy rather than directly against Geoserver.
Depends on a following PR to Geonode.
> Use Geonode proxy for style requests.

- package.json
- src/common/layers/LayersDirective.js
- src/common/layers/partials/layers.tpl.html
BEX-835
Check for style edit permissions per layer
> Apply hasStylePermissions(layer)

- src/common/legend/LegendDirective.js
PSBEX-122
Sends the legend graphics request through the proxy
N/A
> Proxy the legend graphic

- package.json
Fixes bugs with symbol styling.
BEX-882, BEX-883
Updates the story tools dependency.
> Update story-tools dependency

- src/common/map/MapService.js
refs: BEX-867
Mixes in the appropriate missing metadata for workspaces.
> Fix for missing workspace metadata

- src/common/map/MapService.js
BEX-932
This prevents the user from panning off-world.
> Limit extent

- package-lock.json
- package.json
BEX-890
Upgrades to the alpha8 version of the story tools package.
Related commit: https://github.com/boundlessgeo/story-tools/commit/1e089b456f73a34c774d77dd2981fc10672f4304
> Bump-story tools version

- package-lock.json
> Fix commit hash for esprima

- src/app/locales/en.js
- src/app/locales/es.js
- src/common/map/MapSaveDirective.js
- src/common/map/MapService.js
- src/common/map/partial/savemap.tpl.html
- src/common/refresh/RefreshService.js
Add the map refresh interval as a configurable settings.
> Refresh interval config

- package-lock.json
> bump esprima hash

- src/common/featuremanager/FeatureManagerService.js
The recalculate parameter specifies whether to recalculate any bounding boxes for a feature type.
> Recalculate the bounding box for a feature type

- bower.json
- build.config.js
- src/app/app.js
- src/app/app.less
- src/app/locales/en.js
- src/app/locales/es.js
- src/common/map/MapModule.js
- src/common/map/MapService.js
- src/common/map/MapShareDirective.js
- src/common/map/partial/sharemap.tpl.html
- src/index.html
__Part of the "UN work" that Product requested to be merged__
[PSBEX-12](https://issues.boundlessgeo.com:8443/browse/PSBEX-12)
Implements map "sharing" functionality.
* Add button near the map title that will open a modal.
* Button will not appear for new, unsaved maps.
* Modal contains the URL of the current map and a button to copy to clipboard.
* Update browser location after saving the map.
* Open the share map modal after saving the map.
[PSBEX-12](https://issues.boundlessgeo.com:8443/browse/PSBEX-12)
> PSBEX-12: Share Map

- bower.json
- build.config.js
- package-lock.json
- package.json
- src/app/app.js
- src/app/app.less
- src/app/locales/en.js
- src/app/locales/es.js
- src/common/addlayers/ServerService.js
- src/common/addlayers/UnifiedSearchDirective.js
- src/common/featuremanager/FeatureManagerService.js
- src/common/layers/LayersDirective.js
- src/common/layers/partials/layers.tpl.html
- src/common/layers/style/layers.less
- src/common/map/MapModule.js
- src/common/map/MapSaveDirective.js
- src/common/map/MapService.js
- src/common/map/MapShareDirective.js
- src/common/map/partial/savemap.tpl.html
- src/common/map/partial/sharemap.tpl.html
- src/common/refresh/RefreshService.js
- src/index.html
> Ps/pki 1.4.11.1 merge

- src/app/app.js
- src/app/app.less
- src/common/addlayers/LayersService.js
- src/common/featuremanager/AttributeEditDirective.js
- src/common/featuremanager/FeatureManagerService.js
- src/common/featuremanager/partial/attributeedit.tpl.html
- src/common/map/MapService.js
- src/common/map/style/map.less
- src/common/tableview/TableViewDirective.js
- src/common/tableview/partial/tableview.tpl.html
- src/index.html
PSBEX-192
Merges commits relevant to `1.4.12.2` of Exchange into `ps/pki`, which will be pushed back to `master` for inclusion of pki in the next release.
N/A
PSBEX-192
> Ps/pki 1.4.12.2

- package-lock.json
> bump story tools
