src/common/legend/LegendDirective.js
This is a fix for https://github.com/boundlessgeo/exchange/issues/3
The server object's 'url' property is incorrect when the Python Corsa library is being used to proxy requests to GeoServer. Using 'server.virtualServiceUrl' fixes this issue.
=> Use virtual service URL to request legend icon if available

src/common/addlayers/LayersService.js, src/common/addlayers/RegistryLayersDirective.js, src/common/addlayers/RegistryLayersDirective.spec.js, src/common/addlayers/ServerService.js
This PR replaces `layerInfo.Name` with `layerInfo.LayerId` in the registry directive. Some layer names are not unique, which results in multiple layers being selected based on a single click in the registry cart. However, all layer IDs are unique, so basing the cart selection on this attribute avoids such a conflict. Unit tests have also been updated to account for this change.
=> Replace layer name with layer id in registry cart

src/common/addlayers/ServerService.js, src/common/addlayers/ServerService.spec.js, src/common/configuration/ConfigService.js, src/common/layers/partials/layers.tpl.html, src/common/map/MapService.js, src/index.html
This PR:
- Adds logic to assemble a REST query to retrieve registry layers rather than using a POST request, as this method is causing problems in Exchange. 
- Replaces some unsupported OL methods currently being used for Heatmap generation. The heatmap functionality is still not fixed.
=> Use GET request for registry results

src/common/addlayers/RegistryLayersDirective.js, src/common/addlayers/partials/registryLayers.tpl.html, src/common/configuration/ConfigService.js
This PR fixes the pagination display on the registry modal so that results appear as `10/23`, `20/23`,  `23/23`; rather than `10/23`, `10/23`, `10/23`.
=> Fix pagination display on registry modal

src/common/addlayers/partials/addlayersfilter.tpl.html, src/common/configuration/ConfigService.js
Ng-repeat wasnt populating the dropdown menu of the registry modal in some sessions. Also replacing default registry endpoints in the config service because the current registryUrl is down.
=> Replace ng-repeat with ng-options in catalog dropdown

src/common/addlayers/LayersService.js
Fixes recording titles of registry layers rather than id numbers.
[[NODE-265]](https://issues.boundlessgeo.com:8443/browse/NODE-265)
=> Correctly record name for registry layers

bower.json, package.json, src/common/addlayers/AddLayersFilterDirective.js, src/common/addlayers/LayersService.js, src/common/addlayers/RegistryLayersDirective.js, src/common/addlayers/RegistryLayersDirective.spec.js, src/common/addlayers/ServerService.js, src/common/addlayers/ServerService.spec.js, src/common/addlayers/partials/addlayersfilter.tpl.html, src/common/addlayers/partials/registryLayers.tpl.html, src/common/configuration/ConfigService.js, src/common/map/MapService.js
* Integrate Maploom registry with a agnostic search API
* Multi catalog list support 
* Filter search by text, date, spatial
* Histogram bug fixed
=> Configuring Maploom to work with search API

src/common/addlayers/LayersService.js, src/common/addlayers/ServerService.js, src/common/configuration/ConfigService.js, src/common/map/MapService.js
This PR adds support in the map service and server service for the Esri World Topographic map and also fixes a couple of small Registry-related bugs. Users can now add the World Topo layer from the server modal.
=> Add Esri World Topo Map Support

src/common/addlayers/ServerService.js, src/common/configuration/ConfigService.js, src/common/map/MapService.js
This PR supports Esri WMTS base maps that rely on EPSG:4326. The tiling scheme is slightly different for these, hence the `tileUrlFunction` that gets used in the layer initialization.
=> Handle EPSG:4326 Esri WMTS Services

src/common/addlayers/ServerService.js
Currently, if a user adds an Esri rest service layer config to the config service, the metadata (name, title) gets overwritten by the default Esri layer config. This PR fixes that issue.
=> Prefer gxp_arcsource configService layer configs to default

src/common/map/partial/savemap.tpl.html
Removes @placeholder from <textarea> in Map Save dialog.  This fixes the bug in translation bug for IE where an error dialog would be displayed.
IE has quirks with handling <textarea>s.  This removes a translation directive that was throwing up an error dialog by removing the "placeholder" attribute. The abstract content was moved into the text area body to allow it to be populated when an abstract has already been created.
refs: JIRA / NODE-512 (commit message erroneously refers to 522)
=> Removed placeholder translation which fails in IE

src/common/configuration/ConfigService.js, src/index.html
* Adds the ability to detect and properly append the port to the base URL.
* When a catalog list is empty, it's JSON fails to parse, this wraps catalog parsing in a try {} statement to keep it from preventing proper startup.
No ticket/issue at this time. I found it during dev-environment standup.
MapLoom's configuration service was not honouring running on ports other than 80
=> Add Port Support and Fix Catalog List Startup Bug

bower.json, build.config.js, src/app/app.js, src/app/locales/en.js, src/common/tableview/TableViewDirective.js, src/common/tableview/TableViewService.js, src/common/tableview/partial/tableview.tpl.html
Adds CSV Export to the table view of MapLoom.
This work is a merge from the feature development done by Yancy seen here: https://github.com/boundlessgeo-yancy/MapLoom/tree/csv_download
NODE-336
=> Add CSV Export to TableView

geonode_config.js, src/common/addlayers/AddServerDirective.js, src/common/addlayers/ServerService.js, src/common/addlayers/ServerService.spec.js, src/common/configuration/ConfigService.js, src/common/map/MapService.js, src/index.html
This changeset is necessary to prevent MapLoom from trying to load http
schema URLs when running on HTTPS.  When http URLs are accessed the end user
will get a mixed content warning which can cause confusion and make
potentially insecure requests.
All configured sources will also be stripped of their leading schema in order
to prevent them from being accessed without HTTPs.
Prevents "http" access when the application is loaded over "https".
NODE-341
=> Removed http schema from URLs

src/common/refresh/RefreshService.js
When a layer was not a GeoGig layer it would not iterate the refresh loop to check the next layer,
this has been fixed
Fixes the GeoGig test loop in the RefreshService.
NODE-256
=> Refresh service fixed for mixed layer types

src/common/addlayers/ServerService.js, src/common/geogig/GeoGigService.js, src/common/history/HistoryPanelDirective.js, src/common/history/HistoryPanelDirective.spec.js, src/index.html
Fixes two bugs:
1. Geogig was not showing up in the Unified Layer search because there was no hooks in the Layer's API in GeoNode.  This now supports a "geogig_link" attribute when returned from that API.
2. Fixes bugs when the author and/or author's name is undefined.
NODE-562, NODE-628
=> Fix GeoGig with Unified Search

src/common/map/partial/savemap.tpl.html, src/index.html
Small translate module issues once again.
- IE does not like value= being set on <textarea>s
- Measure tool was using "Measure" instead of "measure" as the key.
Fixes an IE bug that was causing the error dialog to appear.
NODE-26
NODE-512
=> Fixed IE Map Savings / Recall Bugs

src/common/map/MapService.js, src/common/map/MapService.spec.js, src/index.html
- Config is scrubbed on input to remove erroneous layer types.
- MapService will no longer throw an error when a server is
null and it's looking to check the ptype.
Fixes a bug in MapLoom that caused both a startup-error message and a broken "background" layer to show in new maps.
NODE-650
=> Fix for broken "background" layer after geonode upgrade.

src/common/addlayers/ServerService.js, src/common/updatenotification/UpdateNotificationDirective.js
JSESSIONID cookie is used to relate permission to geoserver,
but is limited to the /geoserver path.  This was not working with
/wfsproxy/. Also, GeoGig returns the geometry as an array and the
code assumed it was a simple attribute.
- New code is added to check that the geoserver is 'local' and
will then do an automatic switch to use /wfs
- The WKT parser for notifications now gets the first element of the
geometry array instead of the entire array.
NODE-668
=> Changed the behaviour of the default wfs server.

src/common/map/MapSaveDirective.js, src/common/map/partial/savemap.tpl.html, src/index.html
Adds a method for checking the maploom version inside of the user interface.
It accessed by hovering over the "info" icon in the save map
dialog. There are not many default dialogs and this was a
predictable landing spot.  The icon itself is small and out of the
way.
The version is added into "scope" by using the window variable
MAPLOOM_VERSION, which is an object containing the version string
and the build date.
NODE-661
=> MapLoom version is now available in the UI.

src/less/exchange.less, src/less/main.less
- Created a new exchange.less file that contains all the UI tweaks
for a exchange specific styling.
- The exchange.less is now included in main.less to enable it.
Creates a better looking MapLoom.
NODE-654
=> Created a new "dark" theme for maploom.

src/common/map/MapService.js, src/common/tableview/TableViewService.js
Restores heatmap functionality.
- Fixed request issue causing features to be returned
in their native projection instead of the map projection.
- Fixed bug where the bbox/extent was not being filtered without
other active layer filters.
- Cleaned up legacy settings on objects that are no longer needed
with openlayers.
NODE-676
=> Fixed heatmaps!

src/common/map/MapService.js
The map location tracking was causing a litany of usability
issues.  The most egregious was causing an error when using the
back button.  This has been resolved by simplifying the code a
little and discovering that using the getRealWindow function instead of
the default window allowed using location.hash.
NODE-692
=> Fix for back button issues with hash-tracking

src/common/utils/wktparser.js, src/common/utils/wktparser.spec.js
GeoGig has changed to return an array of geometries instead
of a single geometry string.  In various parts of the application,
where the geogig change was passed around for comparison and parsing,
this was causing a number of failures.
- The parser has been tweaked to detect when an array has been
passed in and will parse the first geometry and return it.
- A test has been added to ensure that this functionality works
correctly.
NODE-690
=> Tweak for wide ranging wkt.read bug.

src/common/addlayers/ServerService.js, src/common/addlayers/ServerService.spec.js
- Found that registry URLs were not properly being corrected
for use in the application.
- Wrote a new function `cleanTileUrl` which handles the different
possible incoming URL styles: relative, absolute, and schemaless.
- Backed up the handling of those types with appropriate tests.
NODE-684
=> Fix for registry Tile URLs.

src/common/diff/FeaturePanelDirective.js, src/common/history/HistoryPopoverDirective.js
Undefined Authors were throwing exceptions when trying to view
the history panel. This commit fixes that by better handling
cases when the author, author's name, author's email, or the timestamp
is undefined.
NODE-712
=> Fix for undef'd authors throwing exception.

src/common/map/MapService.js
If the user hit the back button too many times it could
throw an exception about the tileRange.  This was because the
resolution was being set to zero due to a set of undefiend
conditions.  This prevents the map from entering that
invalid state.
NODE-705
=> Fix for back-button issue with invalid location.

src/common/addlayers/UnifiedSearchDirective.js, src/common/addlayers/partials/unifiedLayerSearch.tpl.html, src/common/addlayers/style/addlayers.less, src/common/map/partial/savemap.tpl.html, src/less/exchange.less
1. Makes all the "X"s white to make them easier to find agianst
the black titlebars.
2. Adds a Close Button to the Unified Search "Add Layers" dialog.
3. Fixes a text-overflow issues on the "add Layers" dialog.
4. Fixes a bug cuasing overflow issues with the 'Save a Copy' button
on the 'Save Map' dialog.
NODE-706
=> Improvements to the latest UI changes.

src/common/history/HistoryPanelDirective.js, src/common/history/HistoryPopoverDirective.js, src/common/history/HistoryPopoverDirective.spec.js, src/common/history/partial/historypanel.tpl.html, src/common/history/style/history.less
When a layer's initial commit is clicked it would cause an error
as there is no 'previous' commit against which to diff.  The new code
now:
1. Adds a 'disabled' class to those entires.
2. Prevents the diff from being executed.
3. Changes the cursor and puts a grey background on those entries.
NODE-726
=> Prevent the user from clicking on initial commit.

src/common/map/MapService.js
Under certain circumstances, Firefox was creating an undefined
center and/or resolutoin when using the forward and back buttons
to navigate.  This makes for a better test that avoids getting
into a spot where the map gets undefined coordinates.
NODE-711
=> Fix for Forward button in Firefox.

src/common/utils/UtilsModule.js
The date-picker was throwing an error if updateDate() was called
before the scope was able to set the date.  This was causing
an error dialog to be shown to the user when looking at the date panel.
Removing the extra call to "updateDate" and using  dateObjectChanged
has fixed the problem.
NODE-712
=> Fix for datepicker throwing error.

src/common/tableview/TableViewService.js
Safari does not properly support @download nor have
a workable alternative. Instead of downloading the table with
filters, the user is prompted that Safari does not support that
functionality and can download the entire table by clicking Ok.
NODE-744
=> Work around for safari table downloads.

src/index.html
Most services do not work with a trailing "/" and various layers
require that this "/" be absent, however, this is not true for
ArcGIS Rest/tile layers.  This change prevents the trailing "/"
from being removed.
N/A
NODE-751
=> Prevent truncation of ArcGIS Rest URLs.

src/common/addlayers/UnifiedSearchDirective.js, src/common/map/MapDirective.js, src/index.html
- Preview map in 'Add Layers' modal now supports 4326 both
as the base map projection and for displaying selection polygons.
- A new 'previewLayerConf' is available in the config that will
allow for a non OSM tileset to be displayed - currently only
ArcGIS Rest Tiles are supported.
NODE-755
=> Added support for 4326 Preview Mapping.

src/common/addlayers/ServerService.js, src/common/legend/LegendDirective.js, src/common/legend/partial/legend.tpl.html
Adds support for registry layers which have a legend_url
attribute.
- ServerService.js is updated to input, and clean, legend_urls
and add them to the layer's config.
- LegendDirective has been updated with a custom filter for
whether a layer should be displayed in the legend.
- The template for LegendDirective has been updated to use that
function.
_NOAA Now Coast, from Registry, Including Legend_
NODE-530
=> Add support for Registry legend_url's.

src/common/addlayers/ServerService.js
Sources end up described as an object and not an array,
so the loop was not able to find the ArcGIS source index. This fix
uses object key iteration instead of array iteration. To find the
correct source-id.
=> Fix for ArcGIS baselayer specification.

src/common/addlayers/ServerService.js, src/common/map/MapService.js
1. Removed the old key from the files.
2. Added the ability to parse the "apiKey" from the source
definition and place it in the layerConfigs.
NODE-796
=> Fix for Bing Maps API Key

src/common/addlayers/UnifiedSearchDirective.js, src/common/map/MapDirective.js
1. Limits the user from panning to substantially out of bounds areas in the preview/filter map.
2. Previously the map did not reset when the user clicked
"Clear all", this now signals the map to reset and fixes a\
bug in which the map can be undefined
NODE-791
=> Fix Quirks with the BBOX Filter

src/app/locales/en.js, src/app/locales/es.js, src/common/addlayers/UnifiedSearchDirective.js, src/common/addlayers/partials/unifiedLayerSearch.tpl.html, src/common/utils/LoadingDirective.js, src/common/utils/partial/loading.tpl.html
The previous search dialog would show the user that they could
not find any layers, even before any search was executed. This caused
some confusion as one of the filters must be selected *before*
a search will execute.  This new version of the dialog attempts
to make that more clear by:
1. Showing a 'spinner' while the user is searching.
2. Adding first-time help test to the layers list in order to
instruct the user to use the options at left to start a search.
This also includes a small update to the 'spinner' to allow it to be labeled. 
NODE-783
=> Add prompt and a spinner for the Unified Search Dialog.

src/common/addlayers/UnifiedSearchDirective.js
After switching to the new integrated search functionality,
types other than layers were showing up in the add layers search.
This was causing MapLoom to attempt to add things to the map
that weren't layers.
NODE-774
=> Filter out non-layers from search.

src/common/updatenotification/UpdateNotificationDirective.js
The zoom-to functionality reprojects features as necessary,
this change stops the notification parser from also projecting
the features on intake.
NODE-812
=> Removed incoming feature reprojection for notifications.

src/common/tableview/TableViewDirective.js
The geometries in the table were already in the map projection.
This change removes the 'double reprojection' which fixes the bad
extent being used for zooming to the feature on the map.
NODE-834
=> Removed Feature Reprojection in Tableview

src/common/diff/FeatureDiffService.js
1. The diff service was trying to call the Geogig service
with 'undefined' as the newTreeish which was causing a failure.
2. To prevent that error (and others), the diff service will now
check to ensure that newCommit and oldCommit are defined, and if not,
substitute an appropriate reference to the start-or-end of the tree,
(00000000 or HEAD).
NODE-690
=> Created associations for 'undefined' commits.

src/common/legend/LegendDirective.js
Heatmaps were creating a new layer without a 'config' in the metadata,
a situation which the legend was not prepared to handle.  Now the
Legend will check to ensure config is defined before trying to examine
it.
NODE-854
=> Fix legend detection bug with heatmaps.

src/common/featuremanager/FeatureManagerService.js
Adding the modify interaction while adding a feature was causing
event clash with drawing.  This error was handled differently
across browsers.
Tested with IE11, Chrome 57, FF (latest).
N/A
NODE-862
=> Removed erroneous addModify.

src/common/search/SearchDirective.js, src/common/search/SearchDirective.spec.js, src/common/search/SearchService.js, src/common/search/SearchService.spec.js, src/common/search/partial/search.tpl.html
Extends the use of GeoQuery integration through reported data in the search bar. By default shows just the name or name and country code, but the search panel is expandable to view additional data.
Search query:
Expanded data:
N/A
=> Utilize GeoQuery data within MapLoom search

src/common/map/MapService.js
Sometimes metadata comes back as null/undef'd on dynamic layers,
the new search stuff was not checking for it.
N/A
NODE-904
=> Forgotten null metadata check.

src/common/featuremanager/FeatureInfoBoxDirective.spec.js, src/common/featuremanager/FeatureManagerService.spec.js
Adds more unit tests to address what was merged in [PR#91](https://github.com/boundlessgeo/MapLoom/pull/91), mainly FeatureInfoBoxDirective.
N/A
N/A
=> Added tests for geoquery changes

src/common/featuremanager/style/featuremanager.less
The box was getting buried as the z-level layout was
no specified.  Putting on a sufficiently high z-level
has allowed the popup box to float to the top.
NODE-304
=> Added z-index directive to popup css.

src/common/addlayers/ServerService.js, src/common/map/MapService.js
Fix the way that bbox was determined for wmsc layers
when they come from unified search.
NODE-863
=> Fix for raster bbox issues.

src/common/layers/partials/layers.tpl.html
In the sidebar, use a layer's `name` property if it exists. If it doesn't, defaults to `title`
[NODE-1036](https://issues.boundlessgeo.com:8443/browse/NODE-1036)
=> Utilize a layer's name property if it exists

bower.json, build.config.js, src/common/diff/FeatureDiffService.js, src/common/diff/FeaturePanelDirective.js, src/common/diff/partial/featurepanel.tpl.html, src/common/diff/style/diff.less, src/common/featuremanager/AttributeEditDirective.js, src/common/featuremanager/FeatureInfoBoxDirective.js, src/common/featuremanager/partial/attributeedit.tpl.html, src/common/featuremanager/partial/featureinfobox.tpl.html, src/common/geogig/GeoGigService.js, src/common/map/MapService.js, src/common/tableview/TableViewDirective.js, src/common/tableview/TableViewService.js, src/common/tableview/partial/tableview.tpl.html
Allow the user to configure attribute visibility in Exchange for a given layer and have MapLoom honor it.
Cherry-picked from @boundlessgeo-yancy 's contribution to another branch, this completes the workflow such that the web mapping client and the mobile form for IOS and Andriod all display the same information for the layers attributes.
=> Using exchange attribute options in the appropriate views.

src/common/featuremanager/partial/featureinfobox.tpl.html
Now users can only create spatial filters using features with geometries, instead of allowing spatial filters to be created from any feature and then displaying an error.
Resulting feature info popup:
[NODE-1177](https://issues.boundlessgeo.com:8443/browse/NODE-1177)
1. Upload a GeoTIFF layer.
2. Publish the layer.
3. Create a map from the layer.
4. Click on a feature in the layer.
5. The "Use this feature in a spatial filter" will no longer be displayed in the feature info popup.
=> Restricting spatial filters to features with geometries

src/common/featuremanager/FeatureManagerService.js
The eval function throws an error if the mediaItem is something like "myImg.jpg".  In this case, it should be resolved by the fileservice url template.
=> Fix feature images that are referred to by file name instead of base64.

src/common/featuremanager/FeatureManagerService.js
The feature info box popup was using the layer's CRS to reproject the geometry from the WMS GetFeatureInfo, but the geometry was already in the correct projection.
=> Fix issue with geometry reprojection in feature info popup.

.travis.yml, src/common/addlayers/ServerService.js, src/common/featuremanager/FeatureInfoBoxDirective.js
1. Removes use of `String.include` as it was causing test failures.
My suspcion is that this is due to an issue with the PhantomJS
test runner not supporting this specific string function. It may have
worked in browser but was failing in the testing environment.
2. Restores pin/unpin functions that were removed in a merge.
As the tests for pinning features still existed, I assume the feature
is still in the application. The functions are restored and the tests
now pass.
=> Fix all the tests

src/common/featuremanager/FeatureManagerService.spec.js, src/common/utils/Globals.js
Added additional checks and tests to ensure that the escapeXml
function handles malformed inputs. This will not properly return
strings, numbers, and non-objects such as null and undefined.
bex-462
=> Fix for escapeXml with non-strings.

src/common/addlayers/ServerService.js, src/common/geogig/GeoGigService.js
The code for parsing bounding boxes is specific to WMS 1.1.X
GetCapbilities format. Newer version of GeoServer default to WMS 1.3.
This forces the GetCapabilities call to use 1.1.1 and removes a line
of dead projection parsing code which was causing an error when the
server is configured without GeoGig.
https://github.com/boundlessgeo/MapLoom/pull/112
BEX-418
=> Specify WMS Version for GetCapabilities

src/common/addlayers/ServerService.js
Removed the getcapabilities call which populated information
for the server object.
Each Layer also has a GetCapbilities call to populate its
individual information.  See `src/common/addlayers/ServerService.js:544`,
where the layers get their info fetched. While this does not fix the
underlaying issue with GeoServer throwing errors, it may prevent fallout
from layers which are working when in environment where there are broken
layers.
BEX-289
=> Remove GetCapabilties call which was causing failures.

src/common/legend/LegendDirective.js, src/common/map/MapService.js
1. Created a new topic `layers-styled` that is broadcast
whenever a layers style is updated.
2. Added a new `_dc` - "defeat cache" to the end of the
legend request.
3. Whenever the `layers-styled` message is broadcast,
the legend directive changes the `_dc` value for all legends
causing them to refresh.
BEX-413
=> Legends now refresh when the styles change

src/common/tableview/partial/filteroptions.tpl.html
Bootstrap was made angry and not picking up the drop-down controls.
Added additional 'hints' for Bootstrap to automatically work the
drop-down tools.
BEX-466
=> Fix for advanced filters

src/common/addlayers/ServerService.js, src/common/map/MapService.js
This error is related to using GetCaps 1.1.1. The projection
was not parsed correctly as the Openlayers GetCaps parser assumes
the 1.3.0 nomenclature.  Therefore, the layer's SRS was not transformed
or interpreted as expected (that is as the CRS as the 1.3.0 spec calls for).
This fix reverts the change to the 1.1.1 version of GetCaps but ultimately
still fixes the zoom-to errors that were happening before.
BEX-469, BEX-418, PR #114
=> Fix Attribute Editing

src/common/featuremanager/FeatureManagerService.js
Add crs null check and reproject features only if they don’t match the map projection
=> Add crs null check

src/common/featuremanager/FeatureManagerService.js, src/common/map/MapService.js
1. Added a new getGetFeatureInfo function to the mapproxy_tms
layer type's XYZ source.
2. Created a new parser for ESRI's GetFeatureInfo XML default format.
BEX-243
=> Support GetFeatureInfo on Remote WMS

src/common/tableview/TableViewDirective.js, src/common/tableview/TableViewService.js
Fixes an issue where WPS calls are failing because of a missing workspace in tableview
=> Prepend workspace name to typename in tableview

src/common/map/MapService.js
REST services don't support get feature info or the
legend_url from registry.  This prevents the 'split'
error from happening as it does not add a getGetFeatureInfo
function to the XYZ layers for ArcGIS REST services.
=> Prevent calling GetFeatureInfo on REST services

src/common/addlayers/ServerService.js
This PR addresses the issue where loading a saved map attempts to lazy load the layer which results in the layer being disabled.
=> Do not lazy load if viewing a saved map

src/common/map/MapService.js
=> fixing remote services visibility

src/common/map/partial/savemap.tpl.html
Disallows the user to save a map in MapLoom if they have yet to specify a title. The button will remain disabled until a nonempty string exists in the "Title" form field.
N/A
=> Require a non-empty title to save a map

src/common/layers/LayersDirective.js, src/common/layers/partials/layers.tpl.html
Limits font families to serif and sans-serif.
refs: BEX-568
Depends on: https://github.com/boundlessgeo/story-tools/pull/1
=> Limit the avilable font types

src/common/geogig/GeoGigService.js
Allows Maploom to set the geomType when `gml:SurfacePropertyType` or `gml:MultiSurfacePropertyType` is returned from the WFS DescribeFeature request.
The snippet below is an example response that raised the issue.
```
<?xml version="1.0" encoding="UTF-8"?><xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:geonode="http://geonode" xmlns:gml="http://www.opengis.net/gml" elementFormDefault="qualified" targetNamespace="http://geonode">
<xsd:import namespace="http://www.opengis.net/gml" schemaLocation="https://exchange.boundlessgeo.io/geoserver/schemas/gml/3.1.1/base/gml.xsd?access_token=d0x1l720SkSKj63EwOgVg5LhO7rQjM"/>
<xsd:complexType name="policedistrict_c9f6e591Type">
<xsd:complexContent>
<xsd:extension base="gml:AbstractFeatureType">
<xsd:sequence>
<xsd:element maxOccurs="1" …
```
=> Allow SurfacePropertyType and MultiSurfacePropertyType

src/common/layers/style/layers.less
This will have the popup menus inside of the style
editor pop "up" instead of down. This works better
in most cases for spacing.
refs: BEX-570
=> CSS change to make "pop UP" menus.

src/common/featuremanager/FeatureManagerService.js
Fixes https://issues.boundlessgeo.com:8443/browse/BEX-606
=> Make sure geometry_name is set when reprojecting features

src/common/addlayers/ServerService.js, src/common/map/MapService.js, src/index.html
1. Proxy WMS requests through the GeoNode proxy.
2. Handle the case where the source WMS does not support 900913 projections.
3. Prevent remote services from having their URL 'trimmed.'
BEX-556, BEX-557
=> Working remote services

src/common/addlayers/ServerService.js, src/common/legend/LegendDirective.js
- Only prompt when a `requireLogin` property is set to true on the source.
- Add support for remote WMS legends.
- Limit legend support to ONLY WMS (no ESRI services).
BEX-557
=> Bex 557 remote service ui

src/common/layers/style/layers.less
The popups have DOM scoping issues that cause
them to occasionally be buried under other elements,
this limits the height minimizing the effect.
refs: BEX-570
=> Fix for over grown attribute popups.

src/common/diff/FeatureDiffDirective.js
The undo button would allow invalid requests undo requests.
The new check ensures that both the old and new commits:
1. Are valid.
2. Are not the same commit.
BEX-611
=> Undo Button - Smarter check for valid commits

src/common/diff/FeatureDiffDirective.js, src/index.html
When ArcGIS REST services are found in the configuration,
they now check that the trailing "/" exist
BEX-639
=>  Fix for Arc-rest services without a trailing "/"

src/common/addlayers/ServerService.js, src/common/legend/partial/legend.tpl.html, src/common/map/MapService.js
1. Removes the layers-count check for loaded WMS server configurations.
There are some situations in the new setup that can have WMS GetCaps
return zero layers. This removes that check and treats the server
as valid so long as the response is valid (200 and parseable).
2. Added an onError check to legend <img>s
Hide images which return an XML error, not all services support
a GetLegendGraphic Request, the image will now be hidden in that
case.
3. Remove the broken WFS request for remote services.
There's no WFS proxying for remote layers.  This makes any
remote service return as read-only.
BEX-646
=> Various small fixes for loading remote services.

src/common/timeline/TimelineService.js
Moved the time delay from 1000ms to 5000ms, with only a 1000ms
delay, the layer was invalidating before it had the chance to load
the next set of tiles.
BEX-676
=> Delay the time between intervals

src/common/map/MapService.js
Animation was causing the zoom-to action to fail
to re-render the map.
BEX-696
=> Disable animation by default for zoomto

src/common/map/MapService.js
ESRI layers added from search did not have their BBOX set properly.
This ensures that the bbox is set properly when the layer is loaded
at start up (Loading a map, create map from layer) and when the layer
is added to the map from the search (Add Layers Dialog).
refs: BEX-695
=> Fix "zoomto" issue on added layers.

src/common/addlayers/ServerService.js
With out this fix, when a user attempts to create a map from a copied map, the layers are disabled. This change sets server.lazy to false when copy= is in the url params so the config can be hydrated.
=> account for copy= so that layers load correctly for copied maps.

src/common/addlayers/ServerService.js
See title.
These are for ArcREST `f=pjson` and WMS `GetCapabilities` calls.
=> Followup to 2ed6819; more double proxy fixes for pki route

src/index.html
Styling will now be disabled when the user does not have the
styling permissions.
refs: BEX-826
=> Limit style controls to those with the change_style perm.

src/common/addlayers/UnifiedSearchDirective.js, src/common/map/MapService.js
Remote layer's typenames were getting all three colons (source:workspace:layer),
this attempts to detect the best option (name vs typename) and uses it
to create better reliability for rendering the layer.
=> Better typename resolution for remote layers.

src/common/addlayers/ServerService.js
BEX-901
The 'Title:' attribute was not being properly set from the server's
name for the layer.  This is now fixed.
=> Fix for ArcGIS layer titles

src/common/legend/LegendDirective.js
BEX-934
As it is possible to get an "empty" legend panel with a set
of remote services, this will allow the panel to show/hide.  It looks
less broken but doesn't display any data.
=> Remove "length" check from legend.

src/common/layers/LayersDirective.js
BEX-902
When a raster attribute is detected, hide the style
control.
=> Hide Style Control for Raster Layers

src/common/layers/LayersDirective.js, src/common/layers/partials/layers.tpl.html
BEX-905
Some remote layers will not have a usable projection
for the zoom-to button.  This will detect when a valid projection
is present and show the button.  Otherwise, the button will be hidden.
=> Hide Zoom Button when Unavailable

src/common/map/MapService.js
BEX-931
The tile_url was not checking for a trailing "/",
this fixes that oversight.
=> Ensure that ArcGIS URLs end in "/"

src/common/map/MapService.js
PSBEX-169
Specifies a layer from the ArcREST service to be displayed in the map (previously, it always showed the default)
=> Grab correct ArcREST layer for tile services

package-lock.json
Fixes checksum build error: https://travis-ci.org/boundlessgeo/MapLoom/builds/380696450
Possibly jshint is pulling a newer version of esprima, causing the hash not to match. Updating to the expected hash in package-lock.json allows it to build.
=> Fix hash for esprima

package-lock.json, package.json, src/common/map/MapService.js
N/A
Attempts a permanent fix for the esprima hash problems by bumping our jshint version. Additionally resolves the resulting new errors jshint reports.
Before:
Running `npm ci` in MapLoom should fail every once in a while because of an outdated esprima hash. Maybe even `npm install` fails at some point.
After:
The `package-lock.json` file will correctly point to the versions we want due to an updated `jshint`. Running `npm ci` should no longer fail.
N/A
[GVSD-6448](https://jira.gvslabs.com/browse/GVSD-6448)
=> Bump jshint

package-lock.json, package.json, src/common/map/MapService.js
[BEX-976](https://issues.boundlessgeo.com:8443/browse/BEX-976)
Should be a more permanent fix to patching the esprima hash as here: https://github.com/boundlessgeo/MapLoom/pull/186
Attempts a permanent fix for the esprima hash problems by bumping our jshint version. Additionally resolves the resulting new errors jshint reports.
Before:
Running `npm ci` in MapLoom should fail every once in a while because of an outdated esprima hash. Maybe even `npm install` fails at some point.
After:
The `package-lock.json` file will correctly point to the versions we want due to an updated `jshint`. Running `npm ci` should no longer fail.
N/A
[BEX-976](https://issues.boundlessgeo.com:8443/browse/BEX-976)
=> Jshint bump

src/common/addlayers/ServerService.js, src/common/layers/style/layers.less, src/common/map/MapService.js
Added support for XYZ maps from the geonode config
Example:
```python
MAP_BASELAYERS = [{
"source": {"ptype": "gxp_olsource"},
"type": "OpenLayers.Layer",
"args": ["No background"],
"name": "background",
"visibility": False,
"fixed": True,
"group":"background"
}, {
"source": {"ptype": "gxp_olsource"},
"type": "OpenLayers.Layer.XYZ",
"args": [
"Mapbox Streets",
["https://bcs.boundlessgeo.io/basemaps/mapbox/streets/{z}/{x}/{y}.png?apikey=add-api-key&version=0.1"],
{
'transitionEffect': 'resize',
'attribution': 'Mapbox 2017'
}
],
"name": "Mapbox Streets",
"visibility": True,
"fixed": True,
"group": "background"
}]
```
=> XYZ maps implementation

src/common/layers/LayersDirective.js, src/common/layers/partials/layers.tpl.html, src/common/layers/style/layers.less, src/common/map/MapService.js
__Part of the "UN work" that Product requested to be merged__
[PSBEX-4](https://issues.boundlessgeo.com:8443/browse/PSBEX-4)
Add a slider for transparency in the layer info section of the left menu.
Does not appear for base layers.
Transparency setting is saved in the map configuration and is used on map load.
[PSBEX-4](https://issues.boundlessgeo.com:8443/browse/PSBEX-4)
=> PSBEX-4: Add Layer Transparency Slider

src/common/map/MapService.js
BEX-1039
ESRI remote layer names are loading differently in Maploom from the main search and within Maploom using the add layer dialog.
As a user I would expect no matter the option used to create a map or add a layer that the layer name should be consistent and the same.
STEPS
- Main search, click or add layers to a workspace to create a map
- Layer loads
or
- Maps, Create Map
- Add layer dialog
- Select and add layer
- Layer named different
https://github.com/boundlessgeo/MapLoom/blob/master/src/common/addlayers/ServerService.js#L586
=> ESRI metadata has capital T Title

src/common/addlayers/LayersService.js
BEX-930
User is seeing some bounding box issues with remote services in Maploom when a new map is created from search. The remote service is added to maploom but zooms to Antartica, if the user is able to click zoom to data without receiving a getcode error, the map redirects and zooms to the correct location.
=> Also check for SRID

src/common/addlayers/UnifiedSearchDirective.js
BEX-889
User is seeing remote service layers showing up disabled when a map is saved with only remote services and then reloaded from Explore Maps. The user is able to successfully add the remote service layers and save the map but when the map is reloaded from Explore Maps, the layers show up disabled.
This issue is occurring when the Add Layer dialog in Maploom is used
STEPS:
- Create map
- Add Remote Services from Add Layer Dialog
- Save map
- Maps, Explore Maps
- Click on the saved map to open
- Layers show up disabled
=> Prevents layers from being disabled.

src/common/addlayers/ServerService.js
BEX-1006
Fixes the issue where the feature popup is not rendered in the correct location after creating new feature. While troubleshooting, I noticed that the error doesn't exist when the map crs is EPSG:4326 which led me to the line of code addressed in this PR which was grabbing the first crs from the list and happened to be EPSG:4326. Rather than taking that approach, the fix looks up the current maps crs in the list of supported crs's and if found, it returns it.
=> Grab the crs that matches the maps crs

src/common/addlayers/ServerService.js, src/common/addlayers/UnifiedSearchDirective.js, src/common/configuration/ConfigService.js, src/common/legend/LegendDirective.js, src/common/map/MapService.js, src/common/utils/Globals.js, src/index.html
New new version of: https://github.com/boundlessgeo/MapLoom/pull/164
All content is the same, but removing extraneous commits and conflicting content with master. 
[PSBEX-192](https://issues.boundlessgeo.com:8443/browse/PSBEX-192)
[BEX-1058](https://issues.boundlessgeo.com:8443/browse/BEX-1058)
Gets pki related MapLoom code, as well as some other fixes, merged back into master. Relates with many other changes in various submodules and Exchange. See the main Exchange PR here: https://github.com/boundlessgeo/exchange/pull/5
**Please test before merging.** The changes here should be "safe", in that MapLoom should work fine even if the commits from other components are not present, although PKI will not be functional.
**Globals.js**
[L319](https://github.com/boundlessgeo/MapLoom/pull/207/files …
=> MapLoom PKI functionality

src/index.html
[BEX-1007](https://issues.boundlessgeo.com:8443/browse/BEX-1007)
Removes the "Save Map" button when the user lacks permissions for adding a map.
[BEX-1007](https://issues.boundlessgeo.com:8443/browse/BEX-1007)
=> Remove save button for unauthorized users
